services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: merchion-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        expose:
            - "9000"
        depends_on:
            - db
        environment:
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=${DB_DATABASE}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}

    nginx:
        image: nginx:alpine
        container_name: merchion-nginx
        restart: unless-stopped
        ports:
            - "8080:80" # Porta do Nginx para servir PHP/Laravel
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: merchion-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3307:3306"
        volumes:
            - dbdata:/var/lib/mysql

volumes:
    dbdata:
